import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using PebelAI.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <header className="border-b border-slate-100">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/">
            <Image src="/pebelai-logo.svg" alt="PebelAI" width={130} height={34} className="object-contain" />
          </Link>
          <div className="flex items-center gap-6 text-[13px] text-slate-500">
            <Link href="/privacy" className="hover:text-slate-900 transition-colors">Privacy</Link>
            <Link href="/about" className="hover:text-slate-900 transition-colors">About</Link>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-[11px] font-semibold tracking-widest text-[#2d8a52] uppercase mb-3">Legal</p>
        <h1 className="text-4xl font-bold text-slate-900 mb-3 tracking-tight">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-12">Last updated: April 19, 2026</p>

        <div className="prose prose-slate max-w-none space-y-10 text-[15px] leading-relaxed text-slate-700">

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>By creating a PebelAI account or using any part of the service, you agree to be bound by these Terms of Service. If you do not agree, do not use PebelAI. These terms apply to all users of the platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Description of Service</h2>
            <p>PebelAI is an AI-powered job application tracker and interview coaching platform operated by Dune AI. The service lets you track job applications, practice interviews with an AI coach, generate tailored Q&A, and download session transcripts as PDFs.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Account Registration</h2>
            <p>You must provide accurate information when registering. You are responsible for maintaining the security of your account and password. You must notify us immediately at <a href="mailto:sahilsahani13@gmail.com" className="text-[#2d8a52] underline">sahilsahani13@gmail.com</a> if you believe your account has been compromised.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the service</li>
              <li>Reverse engineer, scrape, or copy the platform</li>
              <li>Submit content that is abusive, fraudulent, or violates third-party rights</li>
              <li>Use the AI coach to generate misleading or harmful content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. AI-Generated Content</h2>
            <p>Interview questions and answers generated by PebelAI are produced by AI and are provided for practice purposes only. We do not guarantee their accuracy, appropriateness for any specific employer, or fitness for a particular purpose. Always use your own judgment in real interviews.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Intellectual Property</h2>
            <p>The PebelAI name, logo, and platform design are owned by Dune AI. Content you create and enter (job details, personal notes) remains yours. You grant us a limited license to store and process your content solely to provide the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Disclaimer of Warranties</h2>
            <p>PebelAI is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that AI responses will be accurate or complete. Use of AI coaching does not guarantee employment outcomes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, Dune AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of PebelAI, including loss of job opportunities or reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Termination</h2>
            <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time via Settings. Upon termination, your data will be deleted within 30 days unless required to be retained by law.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">10. Changes to Terms</h2>
            <p>We may update these terms from time to time. We will notify you by email or in-app notice. Continued use after changes constitutes your acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">11. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:sahilsahani13@gmail.com" className="text-[#2d8a52] underline">sahilsahani13@gmail.com</a>.</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-slate-100 py-8 mt-8">
        <div className="max-w-3xl mx-auto px-6 flex items-center justify-between">
          <p className="text-[11px] text-slate-400 tracking-widest uppercase">Powered by Dune AI</p>
          <div className="flex gap-5 text-[12px] text-slate-400">
            <Link href="/terms" className="hover:text-slate-700 transition-colors">Terms</Link>
            <Link href="/privacy" className="hover:text-slate-700 transition-colors">Privacy</Link>
            <Link href="/about" className="hover:text-slate-700 transition-colors">About</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
